/** Certification items for the Certifications / QHSE grid (photo layout) */
export const certificationsList = [
  { id: 'iso-9001', title: 'ISO 9001', description: 'Qualité', image: '/strategy-consultation.jpg' },
  { id: 'iso-45001', title: 'ISO 45001', description: 'Sécurité', image: '/team-collaboration.jpg' },
  { id: 'iso-14001-certiphyto', title: 'ISO 14001 / Certiphyto', description: 'Environnement', image: '/placeholder.jpg' },
  { id: 'iso-50001', title: 'ISO 50001', description: 'Énergie', image: '/strategy-consultation.jpg' },
  { id: 'iso-26000', title: 'ISO 26 000', description: 'Sociétale', image: '/team-collaboration.jpg' },
  { id: 'label-marianne-nf', title: 'Label Marianne / NF service', description: 'Service', image: '/audit-analysis.jpg' },
  { id: 'en-9100', title: 'EN 9100', description: 'Aéronautique', image: '/placeholder.jpg' },
  { id: 'iatf-16949', title: 'IATF 16949', description: 'Automobile', image: '/training-expertise.jpg' },
  { id: 'iso-13485', title: 'ISO 13485', description: 'Médical / Marquage CE', image: '/audit-analysis.jpg' },
  { id: 'iso-15085-3834-1090', title: 'ISO 15085 / 3834 / 1090', description: 'Soudure', image: '/placeholder.jpg' },
  { id: 'iso-17025', title: 'ISO 17025', description: 'Laboratoire', image: '/training-expertise.jpg' },
  { id: 'iso-22000-ifs-haccp', title: 'ISO 22000 / IFS / HACCP', description: 'Agroalimentaire', image: '/strategy-consultation.jpg' },
  { id: 'qualiopi', title: 'Qualiopi', description: 'Formation Professionnelle', image: '/audit-analysis.jpg' },
  { id: 'iso-20121', title: 'ISO 20 121', description: 'Activité événementiel', image: '/team-collaboration.jpg' },
  { id: 'evaluation-externe', title: 'Évaluation externe', description: 'Médico-sociaux', image: '/placeholder.jpg' },
  { id: 'label-rse-ecovadis', title: 'Label RSE / ECOVADIS', description: 'Enjeux Sociétaux', image: '/team-collaboration.jpg' },
  { id: 'apsad', title: 'APSAD I7/F7 et I 90', description: 'Assurance', image: '/audit-analysis.jpg' },
  { id: 'fsc-pefc', title: 'FSC & PEFC', description: 'Gestion des forêts', image: '/placeholder.jpg' },
  { id: 'iso-19443', title: 'ISO 19443', description: 'Nucléaire', image: '/strategy-consultation.jpg' },
  { id: 'iso-17020', title: 'ISO 17020', description: 'Inspection', image: '/training-expertise.jpg' },
  { id: 'mase-cefri', title: 'MASE / CEFRI', description: 'Sécurité sur site Client', image: '/team-collaboration.jpg' },
]
